services:
  db:
    image: postgres:15
    container_name: hw25-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=roman
      - POSTGRES_DB=hw25db
    volumes:
      - pg:/var/lib/postgresql/data
    restart: always

  web:
    image: nginx:alpine
    container_name: hw25-web
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    restart: always

volumes:
  pg:
